# Generated by Django 5.1.1 on 2024-09-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='short_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/destinations'),
        ),
    ]
