# Generated by Django 5.1.1 on 2024-09-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destinations_short_desc_alter_destinations_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='level',
        ),
        migrations.DeleteModel(
            name='Tech',
        ),
        migrations.AddField(
            model_name='destinations',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
