# Generated by Django 5.1 on 2024-09-26 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_remove_destinations_level_delete_tech_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinations',
            name='image',
        ),
        migrations.RemoveField(
            model_name='destinations',
            name='time',
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/destinations')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destinations')),
            ],
        ),
    ]
